---
rank: 1
title: The estimates for Ruritania, among others, have changed since the previous
  version. Why is that?
---

There are three reasons why estimates change from one version of the SWIID to the next. The first reason is revisions to the [Luxembourg Income Study](http://www.lisdatacenter.org/our-data/lis-database/documentation/data-revisions-notes/).  As the LIS serves as the standard for SWIID estimates, when Ginis from the LIS change, the SWIID estimates change as well.

The second reason for changes is the addition of more source data for the country. Each new version of the SWIID includes new source data both for (a) years that were not previously available, and (b) earlier years from sources I've discovered since the last update. Adding more source data for a country, particularly when previously available data was scant, holds the potential that the estimates will change.

The third, least obvious reason for changes is the availability of more raw data for other countries. The SWIID estimates for many countries that a relatively data-poor depend at least in part on information from other countries in their region or, for some developing countries, even on other developing countries in other regions (see Figure 4 and discussion in [Solt 2016](../papers/Solt2016)). This means that, given the scarcity of data on [Ruritania](https://en.wikipedia.org/wiki/Ruritania#In_academia), more data---especially more LIS data---for other countries in Ruritania’s region can lead to substantial changes in the estimates for Ruritania.
