---
rank: 3
title: What about Russia and the rest of the former Soviet Union? Yugoslavia? Czechoslovakia?
  Pakistan? Sudan? Ethiopia? Why are there estimates for successor states before they
  actually existed?
---

For countries that have undergone partition, the SWIID estimates for a given year include all of the origin country's then-current territories.  This means that for dates before partition, all of the once united territory is included: estimates for Sudan before 2011, for example, include present-day South Sudan.

Where Ginis are available from before the breakup for the territory of successor states, these Ginis have been standardized like anything else in the source data (the SWIID routine does not make any effort to incorporate information from the origin state into estimates for the successor state).  For example, the estimates for Russia for dates before the breakup of the Soviet Union are for the territories of the USSR that would become Russia after the breakup; there are similar pre-breakup data available for many FSU states, the Czech Republic and Slovakia, and the successor states of the former Yugoslavia.  The resulting estimates are available for use when appropriate, that is, to match the conventions of the other data one may be employing.
