# Site settings
title: Frederick Solt
subtitle: Income Inequality & Its Consequences, Comparative Political Behavior, and Dynamic Comparative Public Opinion
name: Frederick Solt
author: Frederick Solt
email: frederick-solt@uiowa.edu
baseurl: ""
twitter_username: fredericksolt
github_username:  fsolt
gscholar_code: PNwjYEAAAAAJ

# Where things are
source:      .
destination: ./_site
collections: null

# Outputting
permalink: /blog/:year/:month/:day/:title

# Conversion
markdown:    kramdown
highlighter: rouge
lsi: false

