# Site settings
title: Frederick Solt
email: frederick-solt@uiowa.edu
baseurl: ""
twitter_username: fredericksolt
github_username:  fsolt

# Build settings
markdown: kramdown

# Blog
permalink: /blog/:year/:month/:day/:title