---
title: Standardized World Income Inequality Database
---

Cross-national research on the causes and consequences of income inequality has been hindered by the limitations of the existing inequality datasets: greater coverage across countries and over time has been available from these sources only at the cost of significantly reduced comparability across observations.  The goal of the Standardized World Income Inequality Database (SWIID) is to meet the needs of those engaged in broadly cross-national research by maximizing the comparability of income inequality data while maintaining the widest possible coverage across countries and over time.  It incorporates data from the [OECD Income Distribution Database](https://www.oecd.org/social/income-distribution-database.htm), the [Socio-Economic Database for Latin America and the Caribbean](http://www.cedlas.econo.unlp.edu.ar/wp/en/estadisticas/sedlac/) generated by CEDLAS and the World Bank, [Eurostat](https://ec.europa.eu/eurostat/), the World Bank's [PovcalNet](http://iresearch.worldbank.org/PovcalNet/home.aspx), the [UN Economic Commission for Latin America and the Caribbean](http://interwp.cepal.org/sisgen/ConsultaIntegrada.asp?idIndicador=250&idioma=e), national statistical offices around the world, and academic studies while minimizing reliance on problematic assumptions by using as much information as possible from proximate years within the same country.  The data collected by the [Luxembourg Income Study](http://www.lisdatacenter.org/our-data/lis-database/) is employed as the standard.  The SWIID currently incorporates comparable Gini indices of disposable and market income inequality for 198 countries for as many years as possible from 1960 to the present; it also includes information on absolute and relative redistribution.  A full description of the SWIID, the procedure used to generate it, and an assessment of the SWIID's performance in comparison to the available alternatives is presented here: 

[Solt, Frederick. 2020. "Measuring Income Inequality Across Countries and Over Time: The Standardized World Income Inequality Database." _Social Science Quarterly_ 101(3):1183-1199. SWIID Version 9.2, December 2021.](/res/published/solt2020)

There are two ways of using the SWIID.  To directly compare up to four countries in estimated levels and trends of (a) inequality in disposable (post-tax, post-transfer) income, (b) inequality in market (pre-tax, pre-transfer) income, &#40;c) absolute redistribution (market-income inequality minus net-income inequality), or (d) relative redistribution (market-income inequality minus net-income inequality, divided by market-income inequality), or to compare several of these measures in a single country, use the SWIID web app below.  To use the SWIID in statistical analyses, datasets formatted for use in Stata and R are available for download.

<!-- <a class="button" href="swiid_source/">Explore the Source Data</a> -->
<!-- <a class="button" href="swiid_faq/">SWIID FAQ</a> -->
<!-- <a class="button" href="swiid_downloads/">Download the SWIID</a> -->

[<i class="fa-regular fa-compass"></i> Explore the Source Data](swiid_source/){.btn-custom .btn role="button"}  [<i class="fa-solid fa-circle-question"></i> SWIID FAQ](swiid_faq/){.btn-custom .btn role="button"}  [<i class="fa-solid fa-cloud-arrow-down"></i> Download the SWIID](swiid_downloads/){.btn-custom .btn role="button"} 

<iframe src="https://fsolt.shinyapps.io/SWIIDweb" style="border: none; width: 990px; height: 500px"></iframe>

Powered by [RStudio](http://shiny.rstudio.com). 

Please cite the SWIID as follows:

Solt, Frederick. 2020. "Measuring Income Inequality Across Countries and Over Time: The Standardized World Income Inequality Database." _Social Science Quarterly_ 101(3):1183-1199.  SWIID Version 9.2, December 2021.  <br />[Download BibTeX citation](/papers/solt2020/solt2020.bib).