---
date: "2010-07-11 16:46:01"
layout: post
slug: swiid-version-3_0
categories:
- update
- swiid
title: SWIID Version 3.0 is now available!
---

Version 3.0 of the SWIID is now available, with expanded coverage and improved estimates. 

The data on which the SWIID is based have been expanded.  I have collected another 2100 Gini observations (in addition to the 1500 added in v2.0), again with special attention to addressing the thinner spots in the WIID.  As before, these data are available in the replication materials for those who are interested.  Major sources for these data include the <a href="http://iresearch.worldbank.org/PovcalNet/povcalSvy.html" rel="self">World Bank's Povcalnet</a>, the <a href="http://www.depeco.econo.unlp.edu.ar/sedlac/eng/index.php" rel="self">Socio-Economic Database for Latin America</a>, <a href="http://go.worldbank.org/9VCQW66LA0" rel="self">Branko Milanovic's World Income Distribution data ("All the Ginis")</a>, and the <a href="http://laborsta.ilo.org/" rel="self">ILO's Household Income and Expenditure Statistics</a>, but a multitude of national statistical offices and other sources were also consulted.

The SWIID also now incorporates the University of Texas Inequality Project's <a href="http://utip.gov.utexas.edu/data.html" rel="self">UTIP-UNIDO dataset</a> on differences in pay across industrial sectors.  Across countries and years, these data explain only about half of the variation in net income inequality (and much less of gross income inequality) and so yield predictions with prohibitively large standard errors when employed in this way, but where there was sufficient data available, I used the UTIP data to make within-country loess predictions of both net and gross income inequality that informed the SWIID estimates.

The imputation routine used for generating the SWIID was cleaned up: the code now runs more efficiently, and a few errors were corrected.

Many researchers have asked me about using the SWIID to examine questions of redistribution, so I now include in the dataset the percentage reduction in gross income inequality (that is, the difference between the gross and net income inequality, divided by gross income inequality, multiplied by 100) as an estimate of redistribution (&ldquo;redist&rdquo;) as well as its associated standard error (&ldquo;redist_se&rdquo;).  The standard errors for redistribution are particularly important to take into account, as they can often be quite large relative to the size of the estimates.  Observations for redistribution are omitted for countries for which the source data do not include multiple observations of either net or gross income inequality: in such cases, although the two inequality series each still constitute the most comparable available estimates, the difference between them reflects only information from other countries, and treating it as meaningful independent information about redistribution would be unwise.  Similarly, because the underlying data is often thin in the early years included in the SWIID, redistribution is only reported after 1975 for most of the advanced countries and only after 1985 for most countries in the developing world.

As always, I encourage users of the SWIID to email me with their comments, questions, and suggestions.
