---
title: Teaching
---

I teach undergraduate and graduate courses on comparative politics and quantitative methods.  Current students should refer to [ICON](https://icon.uiowa.edu/) for the most up-to-date information on their courses. <br />

### Fall 2022

POLI 1400: Introduction to Comparative Politics

POLI 1449: Introduction to European Politics
<br />


### Spring 2022

POLI 1400: Introduction to Comparative Politics

POLI 7450: The Politics of Economic Inequality
<br />

### Fall 2021

POLI 1400: Introduction to Comparative Politics

POLI 1449: Introduction to European Politics
<br />

### Spring 2021

POLI 1400: Introduction to Comparative Politics

POLI 1800: Introduction to the Politics of Class and Inequality
<br />

### Fall 2020

POLI 1400: Introduction to Comparative Politics
<br />

### Spring 2020

POLI 1400: Introduction to Comparative Politics

POLI 7450: Comparative Public Opinion
<br />

### Fall 2019

POLI 1400: Introduction to Comparative Politics
<br />

### Spring 2019

POLI 1400: Introduction to Comparative Politics

[POLI 7002/7450: Computational Methods for Comparative Politics](http://cmcr-class.rbind.io)
<br />

### Spring 2018

POLI 1400: Introduction to Comparative Politics

POLI 2415: Latin American Politics
<br />

### Fall 2017

POLI 1400: Introduction to Comparative Politics

POLI 1800: Introduction to the Politics of Class and Inequality
<br />

### Spring 2017

POLI 1400: Introduction to Comparative Politics

POLI 7450: Comparative Political Behavior
<br />

### Fall 2016

POLI 2415: Latin American Politics

[POLI 7002/7450: Computational Methods for Comparative Politics](http://cmcr-class.rbind.io)
<br />

### Spring 2016

POLI 1400: Introduction to Comparative Politics

POLI 3450: The Politics of Economic Inequality
<br />

### Fall 2015

POLI 2415: Latin American Politics

POLI 7450: The Politics of Economic Inequality
<br />











