---
date: "2014-10-02 10:40:01"
layout: post
slug: swiid-version-5_0
categories:
- update
- swiid
title: SWIID Version 5.0 is available!
---

Version 5.0 of the SWIID is [now available](/swiid/swiid_downloads/), and it is a major update.  A new article of record (currently available as a working paper while under peer review) reviews the problem of comparability in cross-national income inequality data, explains how the SWIID addresses the issue, assesses the SWIID's performance in comparison to the available alternatives, and explains how to use the SWIID data in cross-national analyses.

The new version also marks the debut of the SWIID web application.  The web application allows users to graph the SWIID estimates of any of net-income income, market-income inequality, relative redistribution, or absolute redistribution in as many as four countries or to compare these measures within a single country.  Its output can be downloaded with a click for use in reports or articles.  I hope that it will be of particular value to policymakers, journalists, students, and others who need to make straightforward comparisons of levels and trends in income inequality.

As always, I encourage users of the SWIID to email me with their comments, questions, and suggestions.
